# Gopkg.toml

[[constraint]]
  name = "github.com/kataras/iris"
  version = "10.2.0"

[prune]
  go-tests = true
  unused-packages = true

[metadata.heroku]
  root-package = "github.com/ncmd/jido-go-iris"
  go-version = "1.10"
  install = [ "." ]

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"
